filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
     

setup.template.name: "fiap-logs"
setup.template.pattern: "fiap-logs-*"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "fiap-logs-%{+yyyy.MM.dd}" 

setup.kibana:
  host: "http://kibana:5601"


logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat.log
  keepfiles: 7
  permissions: 0644
