name: Publicar Imagem Docker no Docker Hub

on:
  push:
    branches:
    - dev
jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e Push
        run: |
          docker build -f ./src/Fiap.Api/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/fcg:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/fcg:latest
